name: Tim Gentry Beta
favicon: null
layout_spectrum: 0.6250297385267913
typography_spectrum: 0.16585683613084257
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.4074066486209631
  lightness: 0.3668221721891314
  saturation: 0.8999190067406744
  rhythmicContrast: 0.6152821786236018
purpose: []
